version: '3'

services: 
  postgres:
    image: postgres
    container_name: postgres_db
    env_file:
      - flow.env
    ports:
      - '5432:5432'
  minio:
    image: docker.io/bitnami/minio:2021
    container_name: minio
    ports:
      - '9500:9000'
      - '9501:9001'
    env_file:
      - flow.env
    volumes:
      - ./S3_VOLUME:/data
  minio-mc:
    container_name: minio-mc
    image: minio/mc:latest
    env_file:
      - flow.env
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add myminio http://minio:9000 $$MINIO_ACCESS_KEY $$MINIO_SECRET_KEY) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb myminio/mlflow;
      /usr/bin/mc mb myminio/actualmodel;
      /usr/bin/mc cp --recursive ./starting_models/* myminio/actualmodel/;
      sleep infinity;
      exit 0;
      "
    volumes:
      - ./StartingModels:/starting_models

  mlflow:
    build: mlflow/
    container_name: mlflow
    env_file:
      - flow.env
    ports:
      - '5500:5000'
    command: bash ./run_mlflow.sh  
  airflow:
    build: airflow/
    container_name: airflow
    ports:      
      - '8080:8080'
    env_file:
      - flow.env
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags